DROP TABLE IF EXISTS hw_timestamps;

DROP TABLE IF EXISTS hw_barks;

DROP TABLE IF EXISTS hw_users;

DROP TYPE IF EXISTS volume_lvl;

CREATE TYPE volume_lvl AS ENUM ('High', 'Medium', 'Low');

CREATE TABLE hw_users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE hw_barks (
    bark_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    barks BOOLEAN NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE hw_timestamps (
    ts_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    timestamp TIME(0) NOT NULL,
    comment TEXT NOT NULL,
    volume volume_lvl NOT NULL,
    confirmations INTEGER,
    media_id TEXT NOT NULL,
    userId INTEGER REFERENCES hw_users(user_id) ON DELETE CASCADE NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);