DROP TABLE IF EXISTS hw_timestamps;

DROP TABLE IF EXISTS hw_users;

DROP TYPE IF EXISTS volume_lvl;

CREATE TYPE volume_lvl AS ENUM ('High', 'Medium', 'Low');

CREATE TABLE hw_users (
    user_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    user_name TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE hw_timestamps (
    timestamp TIME(0) NOT NULL,
    comment TEXT NOT NULL,
    volume volume_lvl NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE hw_movies (
    movie_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    poster VARCHAR(2000),
    title TEXT NOT NULL,
    release YEAR NOT NULL,
    barks BOOLEAN NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE hw_shows (

)